version: '3.9'

services:
  master:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: redis-master
    command: ["sh", "-c", "redis-server /usr/local/etc/redis/redis.conf && sleep 5 && ruby /scripts/fill_data.rb"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./fill_data.rb:/scripts/fill_data.rb

  slave:
    image: redis:latest
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - master

  sentinel:
    build:
      context: ./sentinel
      dockerfile: Dockerfile
    container_name: redis-sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    depends_on:
      - master
      - slave